--- #YAML:1.0
name:                GPS-gpsd
version:             0.10
abstract:            Provides a perl interface to the gpsd daemon.
license:             perl
distribution_type:   module
requires:     
    vars                           0
    strict                         0
    IO::Socket:                    0
